train:
  n_epochs: 40
  batch_size: 32
  device: 0
  rl_weight: 0
  loss: "YoloLoss"
  data:
    dataset: "FastSlowBeatDataset"
    fs: 22050
    hop_length: 512
    n_frames: 128
    n_features: 128
    n_channels: 1
    out_features: 2
    n_grids: 16
  model:
    name: "FastSlowResNeXtBeatModel"
    recover_epoch: 
    tagging: "model18"
  optimizer:
    name: "RMSprop"
    params:
      lr: 0.0001
  scheduler:
    name: "ExponentialLR"
    params:
      gamma: 0.8
