train:
  n_epochs: 1000
  batch_size: 64
  device: 0
  rl_weight: 0
  data:
    dataset: "BeatDataset"
    fs: 22050
    hop_length: 512
    n_frames: 256
    n_features: 128
    n_channels: 1
    out_features: 2
    n_grids: 32
  model:
    name: "CNNBeatModel"
    recover_epoch: 
    tagging: "model7"
    start_epoch: 101
  optimizer:
    name: "RMSprop"
    params:
      lr: 0.00001
  scheduler:
    name: "ExponentialLR"
    params:
      gamma: 1.0
